/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WSlugRouteImport } from './routes/w.$slug'

const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/w/$slug': typeof WSlugRoute
}
export interface FileRoutesByTo {
  '/w/$slug': typeof WSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/w/$slug': typeof WSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/w/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/w/$slug'
  id: '__root__' | '/w/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WSlugRoute: typeof WSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WSlugRoute: WSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
